# Generated by Django 4.0.6 on 2022-07-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbook',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
