# Generated by Django 4.0.6 on 2022-07-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_books', '0003_alter_accountbookcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbooklog',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
