# Generated by Django 4.0.6 on 2022-07-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_books', '0004_alter_accountbooklog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbook',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='accountbookcategory',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
